from __future__ import annotations

import json
from pathlib import Path

from oss_remediation_agent.contracts import ToolResult, common_artifact

TOOL = "PRCreationTool"


def create_pr_summary(manifest_path: str, output_path: str, pr_description_path: str, workflow_id: str = "unknown") -> dict:
    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8")) if Path(manifest_path).exists() else {}
    body = "# OSS Vulnerability Remediation\n\nGenerated by the MVP PR Creation Tool.\n"
    Path(pr_description_path).parent.mkdir(parents=True, exist_ok=True)
    Path(pr_description_path).write_text(body, encoding="utf-8")
    summary = common_artifact(
        artifact_id="pr-summary-001",
        workflow_id=workflow_id,
        created_by=TOOL,
        status="ELIGIBLE",
        prTitle="OSS vulnerability remediation",
        prType="PARTIAL_REMEDIATION",
        pullRequestEligibility={"eligible": True, "type": "PARTIAL_REMEDIATION", "reason": "MVP summary generated."},
        remediationSummary=[],
        validationSummary={},
        artifactReferences={"manifest": manifest_path, "prDescription": pr_description_path},
        prBodyMarkdown=body,
    )
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return ToolResult.success(TOOL, "create_pr", output_path, prDescriptionPath=pr_description_path, manifestStatus=manifest.get("status")).to_dict()
